---

- name: Configure selinux permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    masked: yes

- name: Install module
  command: "dnf module -y install php:7.2"

- name: Install packages
  dnf: 
    name: ['mariadb-server','httpd','php','php-pear','php-cgi','php-common','php-mbstring','php-snmp','php-gd','php-xml','php-mysqlnd','php-gettext','php-bcmath','php-json','php-ldap','python3','python3-PyMySQL','epel-release']
    state: present
  
- name: Enabling services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: started
  with_items:
    - mariadb
    - httpd
    - php-fpm

- name: Copy php configuration
  copy:
    src: etc/php.ini
    dest: /etc/php.ini
    owner: root
    group: root
    mode: '0644'


- name: Create a new database with name 'zabbix'
  mysql_db:
    name: zabbix
    state: present

- name: Create database user called zabbix with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: zabbix
    password: 'zabbix'
    priv: 'zabbix.*:ALL,GRANT'
    state: present

- name: Install zabbix repository
  dnf:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/8/x86_64/zabbix-release-4.2-2.el8.noarch.rpm
    state: present

- name: Install library absent in Centos 8.1
  dnf:
    name: http://mirror.centos.org/centos/8.0.1905/AppStream/x86_64/os/Packages/libssh2-1.8.0-8.module_el8.0.0+189+f9babebb.1.x86_64.rpm
    state: present

- name: Install zabbix
  dnf:
    name: ['zabbix-server-mysql','zabbix-agent','zabbix-web-mysql']
    state: present

- name: Getting database schemma
  shell: "gunzip /usr/share/doc/zabbix-server-mysql/create.sql.gz"
  ignore_errors: yes

- name: Importing database schemma
  mysql_db:
    state: import
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/create.sql
  ignore_errors: yes

- name: Copy zabbix configuration file
  copy:
    src: etc/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: '0640'

- name: Enabling zabbix server
  systemd:
    name: zabbix-server
    enabled: yes
    masked: no
    state: started
  with_items:
    - zabbix-server
    - zabbix-agent

- name: restarting php-fpm and httpd
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - php-fpm
    - httpd
