---

- name: Configure selinux permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    masked: yes

- name: Install module
  command: "dnf module -y install php:7.2"

- name: Install packages
  dnf: 
    name: ['mariadb-server','httpd','php','php-pear','php-cgi','php-common','php-mbstring','php-snmp','php-gd','php-xml','php-mysqlnd','php-gettext','php-bcmath','php-json','php-ldap','python3','mysql-python']
    state: present
  
- name: Enabling services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: started
  with_items:
    - mariadb
    - httpd
    - php-fpm

- name: Create a new database with name 'zabbix'
  mysql_db:
    name: zabbix
    state: present

- name: Create database user called zabbix with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: zabbix@'localhost'
    password: 'zabbix'
    priv: 'zabbix.*:ALL,GRANT'
    state: present

- name: Install zabbix related packages
  dnf:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/8/x86_64/zabbix-release-4.2-2.el8.noarch.rpm
    state: present

- name: Install zabbix
  dnf:
    name: ['zabbix-server-mysql','zabbix-agent','zabbix-web-mysql']
    state: present

- name: Install zabbix database schemma
  command: "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u zabbix -p zabbix"