---
# tasks file for zabbix
- name: Configure selinux permissive
  selinux:
    policy: targeted
    state: permissive

  name: Install packages
  dnf: 
    name: {{ item }}

    state: present
  with_item:
    - mariadb
    - httpd
    - php:7.2
    - php
    - php-pear
    - php-cgi
    - php-common
    - php-mbstring
    - php-snmp
    - php-gd
    - php-xml
    - php-mysqlnd
    - php-gettext
    - php-bcmath
    - php-json
    - php-ldap
  
  name: Enabling services
  systemd:
    name: {{ item }}
    enabled: yes
    masked: no
  with_item:
    - mariadb
    - httpd
    - php-fpm



